package com.myproject.safezone.entity;

public enum NotificationType {

    EMERGENCY_ALERT, WEATHER_WARNING, EVACUATION_NOTICE, LOCKDOWN_ALERT, SAFETY_TIP,

    TEST_ALERT, MISSING_PERSON_ALERT, SHELTER_IN_PLACE, ALL_CLEAR, INFORMATIONAL_UPDATE
}
